/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package System.JPanels;

import javax.swing.JOptionPane;
import BD.TPacientes;
import BD.APaciente;

/**
 *
 * @author Sebastian
 * 
 * Interfaz que muestra el formulario para actualizar paciente
 * 
 */

public class ActualizarPaciente extends javax.swing.JPanel {
    private Pacientes panelPacientes;
    /**
     * Creates new form ActualizarPaciente
     */
    public ActualizarPaciente(Pacientes panel) {
        initComponents();
        this.panelPacientes = panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        TxfDocumentoBuscar = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        TxfDocumento = new javax.swing.JTextField();
        TxfNombre = new javax.swing.JTextField();
        TxfTelefono = new javax.swing.JTextField();
        TxfCorreo = new javax.swing.JTextField();
        TxfDireccion = new javax.swing.JTextField();
        TxfEdad = new javax.swing.JTextField();
        BtnActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTextField7.setBorder(javax.swing.BorderFactory.createTitledBorder("Direccion:"));
        jTextField7.addActionListener(this::jTextField7ActionPerformed);

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(572, 415));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxfDocumentoBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Documento:"));
        add(TxfDocumentoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 168, -1));

        BtnBuscar.setBackground(new java.awt.Color(180, 205, 235));
        BtnBuscar.setText("Buscar");
        BtnBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BtnBuscar.addActionListener(this::BtnBuscarActionPerformed);
        add(BtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 80, 20));

        TxfDocumento.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Documento:"));
        add(TxfDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 209, -1));

        TxfNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nombre:"));
        add(TxfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 209, -1));

        TxfTelefono.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Telefono:"));
        TxfTelefono.addActionListener(this::TxfTelefonoActionPerformed);
        add(TxfTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 209, -1));

        TxfCorreo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Correo:"));
        TxfCorreo.addActionListener(this::TxfCorreoActionPerformed);
        add(TxfCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 209, -1));

        TxfDireccion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Direccion:"));
        TxfDireccion.addActionListener(this::TxfDireccionActionPerformed);
        add(TxfDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 209, -1));

        TxfEdad.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Edad:"));
        TxfEdad.addActionListener(this::TxfEdadActionPerformed);
        add(TxfEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 209, -1));

        BtnActualizar.setBackground(new java.awt.Color(180, 205, 235));
        BtnActualizar.setText("Actualizar");
        BtnActualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtnActualizar.addActionListener(this::BtnActualizarActionPerformed);
        add(BtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 90, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Actualizar paciente");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void TxfTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxfTelefonoActionPerformed

    private void TxfCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxfCorreoActionPerformed

    private void TxfDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxfDireccionActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void TxfEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxfEdadActionPerformed

    //Boton para buscar paciente
    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        
        //Obtenemos el documento del paciente
        String doc = TxfDocumentoBuscar.getText();

        //Obtenemos los datos del paciente
        TPacientes tpac = new TPacientes();
        Object[] datos = tpac.buscarPacientePorDocumento(doc);

        //Validamos que el paciente exista
        if (datos == null) {
            JOptionPane.showMessageDialog(this, "Paciente no encontrado");
            return;
        }

        //Ponemos los datos del paciente en cada campo
        TxfNombre.setText((String) datos[0]);
        TxfDocumento.setText((String) datos[1]);
        TxfTelefono.setText((String) datos[2]);
        TxfCorreo.setText((String) datos[3]);
        TxfDireccion.setText((String) datos[4]);
        TxfEdad.setText(String.valueOf(datos[5]));

    }//GEN-LAST:event_BtnBuscarActionPerformed

    //Boton para actualizar los datos del paciente
    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed
        
        //Pasamos los datos para actualizar paciente
        APaciente tpac = new APaciente();
        boolean ok = tpac.actualizarPaciente(
            TxfNombre.getText(),
            TxfDocumento.getText(),
            TxfTelefono.getText(),
            TxfCorreo.getText(),
            TxfDireccion.getText(),
            Integer.parseInt(TxfEdad.getText())
        );

        //Validamos la respuesta del Back
        if (ok) {
            JOptionPane.showMessageDialog(this, "Paciente actualizado correctamente");

            // cerrar ventana
            javax.swing.SwingUtilities.getWindowAncestor(this).dispose();

            // refrescar tabla
            panelPacientes.cargarPacientes();
        }
    }//GEN-LAST:event_BtnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JTextField TxfCorreo;
    private javax.swing.JTextField TxfDireccion;
    private javax.swing.JTextField TxfDocumento;
    private javax.swing.JTextField TxfDocumentoBuscar;
    private javax.swing.JTextField TxfEdad;
    private javax.swing.JTextField TxfNombre;
    private javax.swing.JTextField TxfTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
