/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package System.JPanels;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author Miguel Angel
 * 
 * Esta interfaz define la plantilla de tarjeta
 * para el dashboard
 * 
 */
public class Card extends javax.swing.JPanel {

    private JLabel lblTitulo;
    private JLabel lblNumero;
    
    public Card(String titulo, String numero, Color colorFondo) {
        initComponents(); 
        personalizar();
        setDatos(titulo, numero, colorFondo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTitulo = new javax.swing.JLabel();
        LblCantidad = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(200, 130));
        setPreferredSize(new java.awt.Dimension(200, 130));

        LblTitulo.setText("Nombre");

        LblCantidad.setText("Cantidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(LblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    //Personalizamos la tarjeta
    private void personalizar() {
        // Colores de texto
        LblTitulo.setForeground(new Color(26, 43, 76));   // #1A2B4C
        LblCantidad.setForeground(new Color(10, 18, 36)); // #0A1224

        // Fuentes
        LblTitulo.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        LblCantidad.setFont(new Font("Segoe UI", Font.BOLD, 34));
        LblCantidad.setHorizontalAlignment(SwingConstants.CENTER);

        // Bordes redondeados opcional
        setBorder(new javax.swing.border.LineBorder(new Color(208, 216, 232), 1, true)); // #D0D8E8

        // Fondo por defecto (card principal)
        setBackground(new Color(255, 255, 255)); // Blanco
    }

    //Le damos los datos a la tarjeta
    public void setDatos(String titulo, String numero, Color colorFondo) {
        LblTitulo.setText(titulo);
        LblCantidad.setText(numero);
        setBackground(colorFondo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblCantidad;
    private javax.swing.JLabel LblTitulo;
    // End of variables declaration//GEN-END:variables
}
