/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package System.JPanels;

import Backend.ButtonEditor;
import Backend.ButtonRenderer;
import Backend.DatosConsulta;
import Controller.Controlador;
import com.itextpdf.text.pdf.AcroFields;
import com.itextpdf.text.pdf.PdfReader;
import com.itextpdf.text.pdf.PdfStamper;
import java.awt.Dialog;
import java.io.FileOutputStream;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Juan David
 * 
 * Esta interfaz muestra un resumen de todas las consultas del sistema
 * ademas de un filtro para estas, permite tambien generar un pdf 
 * de alguna consulta
 * 
 */
public class Consultas extends javax.swing.JPanel {
    
    private Ordenes panelOrdenes;
    Controlador cont = new Controlador();

    
    public Consultas(Ordenes panelOrdenes) {
        this.panelOrdenes = panelOrdenes;
        initComponents();
        cargarConsultas();
        diseño();
        
        //Definimos el placeholder del filtro de busqueda
        agregarPlaceholder(TxtBuscar, "Buscar consulta...");
        TxtBuscar.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) { filtrar(); }
            @Override
            public void removeUpdate(DocumentEvent e) { filtrar(); }
            @Override
            public void changedUpdate(DocumentEvent e) { filtrar(); }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnCrear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblConsulta = new javax.swing.JTable();
        TxtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Consultas");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        BtnCrear.setBackground(new java.awt.Color(180, 205, 235));
        BtnCrear.setText("Crear");
        BtnCrear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtnCrear.addActionListener(this::BtnCrearActionPerformed);
        add(BtnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 80, 30));

        TblConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nom Paciente", "Doc Paciente", "Enfermedad", "Observaciones", "Fecha", "N° Orden", "Servicio", "PDF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblConsulta);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 700, -1));
        add(TxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/medicine_9410386.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    //Boton de crear una nueva orden, abre el modal de formulario
    private void BtnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearActionPerformed
        JDialog dialog = new JDialog(
            SwingUtilities.getWindowAncestor(this),
            "Crear consulta",
            Dialog.ModalityType.APPLICATION_MODAL
        );
        dialog.setContentPane(new CrearConsulta(this, panelOrdenes)); 
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_BtnCrearActionPerformed

    //Cargamos las consultas registradas en la base de datos y las pone en una tabla
    public void cargarConsultas(){
        cont.cargarConsultas(TblConsulta);
        
        //Agregamos el boton de descargar PDF
        TblConsulta.getColumnModel().getColumn(8).setCellRenderer(new ButtonRenderer());
        TblConsulta.getColumnModel().getColumn(8)
            .setCellEditor(new ButtonEditor(new JTextField(), id -> {
                generarPDF(id);
        }));

    }
    
    //Generamos el pdf con los datos de la consulta seleccionada
    public void generarPDF(int idConsulta) {
        
        //Obtenemos los datos de la consulta
        Controlador cont = new Controlador();
        DatosConsulta d = cont.obtenerDatosConsulta(idConsulta);

        try {
            
            //Cargamos la plantilla
            String plantilla = "src\\main\\resources\\Plantillas\\consulta_base_template.pdf";
            
            //Nombre del archivo final
            String salida = "Consulta_" + idConsulta + ".pdf";

            //Leemos la plantilla
            PdfReader reader = new PdfReader(plantilla);
            PdfStamper stamper = new PdfStamper(reader, new FileOutputStream(salida));
            AcroFields form = stamper.getAcroFields();

            //Llenamos la plantilla con los datos de la consulta
            form.setField("txtFecha", d.fecha);
            form.setField("txtPaciente", d.paciente);
            form.setField("txtDocumento", d.documento);
            form.setField("txtCIE10", d.cie10);
            form.setField("txtEspecialidad", d.especialidad);
            form.setField("txtObservaciones", d.observaciones);
            form.setField("txtOrden", String.valueOf(d.ordenId));
            form.setField("txtIdConsulta", String.valueOf(d.id));
            form.setField("txtUsuario", String.valueOf(d.usuario));
            form.setField("txtCargo", String.valueOf(d.cargo));
            
            //Ajustamos el PDF para que no se puedan editar los campos
            stamper.setFormFlattening(true);
            stamper.close();
            reader.close();

            JOptionPane.showMessageDialog(null, "PDF consulta generado.");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }

    //Diseño de la tabla de consultas
    public void diseño(){
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255,255,255));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200,200,200),1,true));
        TblConsulta.setAutoCreateRowSorter(true);
        TblConsulta.getTableHeader().setOpaque(false);
        TblConsulta.getTableHeader().setBackground(new java.awt.Color(30, 30, 30));
        TblConsulta.getTableHeader().setForeground(java.awt.Color.WHITE);
        TblConsulta.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

        // Altura de filas
        TblConsulta.setRowHeight(30);

        // Bordes y color de líneas
        TblConsulta.setShowHorizontalLines(true);
        TblConsulta.setShowVerticalLines(false);
        TblConsulta.setGridColor(new java.awt.Color(220, 220, 220));

        // Fuente del contenido
        TblConsulta.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));

        // Renderer para zebra rows + selección personalizada
        TblConsulta.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table,
                    Object value, boolean isSelected, boolean hasFocus, int row, int column) {

                java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                // Color de texto normal
                c.setForeground(java.awt.Color.BLACK);

                if (isSelected) {
                    c.setBackground(new java.awt.Color(30, 144, 255)); // azul suave
                    c.setForeground(java.awt.Color.WHITE);
                } else {
                    // Zebra rows
                    c.setBackground(row % 2 == 0
                            ? new java.awt.Color(245, 245, 245)
                            : java.awt.Color.WHITE);
                }

                return c;
            }
        });

    }
    
    //Filtro de la tabla de consultas
    private void filtrar() {
        String placeholder = "Buscar consulta...";
        String texto = TxtBuscar.getText();
        if (texto == null) texto = "";

        DefaultTableModel model = (DefaultTableModel) TblConsulta.getModel();

        // Obtener sorter actual, si ya existe
        TableRowSorter<DefaultTableModel> sorter = null;
        if (TblConsulta.getRowSorter() instanceof TableRowSorter) {
            sorter = (TableRowSorter<DefaultTableModel>) TblConsulta.getRowSorter();
        }

        // Si está vacío o es placeholder → remover filtro
        if (texto.trim().isEmpty() || texto.equals(placeholder)) {
            if (sorter != null) {
                sorter.setRowFilter(null);   // mostrar todo
            }
            return;
        }

        // Si no hay sorter, crearlo
        if (sorter == null) {
            sorter = new TableRowSorter<>(model);
            TblConsulta.setRowSorter(sorter);
        }

        // Filtro seguro (escapando el texto del usuario)
        sorter.setRowFilter(RowFilter.regexFilter(
            "(?i)" + java.util.regex.Pattern.quote(texto)
        ));
    }


    //Le agregamos un placeholder al campo de filtro
    private void agregarPlaceholder(javax.swing.JTextField campo, String texto) {
        campo.setText(texto);
        campo.setForeground(new java.awt.Color(150, 150, 150));

        campo.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (campo.getText().equals(texto)) {
                    campo.setText("");
                    campo.setForeground(new java.awt.Color(0, 0, 0));
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (campo.getText().isEmpty()) {
                    campo.setText(texto);
                    campo.setForeground(new java.awt.Color(150, 150, 150));
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCrear;
    private javax.swing.JTable TblConsulta;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
