/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package System.JPanels;

import Backend.Cargador;
import Controller.Controlador;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JList;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author Sebastian
 * 
 * Interfaz que muestra el formulario para crear una consulta
 * 
 */
public class CrearConsulta extends javax.swing.JPanel {
    
    private Consultas panelConsultas;
    private Ordenes panelOrdenes;
    private boolean bloqueado = false;
    private String ultimoTexto = "";
    Cargador back = new Cargador();
    Controlador cont = new Controlador();
    
    /**
     * Creates new form CrearConsulta
     */
    public CrearConsulta(Consultas panelConsultas, Ordenes panelOrdenes) {
        
        //Cargamos el panel de ordenes
        this.panelConsultas = panelConsultas;
        this.panelOrdenes = panelOrdenes;
        initComponents();
        
        //Ponemos el JComboBox editable para poder escribir
        CmbCie10.setEditable(true);
        activarBuscador();
        cargarOpciones();
        
        //Ponemos los JComboBox blancos para que no rompa el diseño
        ponerComboBlanco(CmbCie10);
        ponerComboBlanco(CmbEspecialidades);
        ponerComboBlanco(CmbOrdenes);
        ponerComboBlanco(CmbPacientes);
        jTextArea1.setBorder(null);
        jScrollPane2.setBorder(null);
        jScrollPane2.setViewportBorder(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CmbCie10 = new javax.swing.JComboBox<>();
        CmbPacientes = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxaObservaciones = new javax.swing.JTextArea();
        CmbOrdenes = new javax.swing.JComboBox<>();
        BtnGuardar = new javax.swing.JButton();
        BtnCrearOrden = new javax.swing.JButton();
        CmbEspecialidades = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setPreferredSize(new java.awt.Dimension(600, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CmbCie10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Seleccione una enfermedad"));
        CmbCie10.setDoubleBuffered(true);
        CmbCie10.addActionListener(this::CmbCie10ActionPerformed);
        add(CmbCie10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 220, 50));

        CmbPacientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CmbPacientes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Seleccione un paciente"));
        add(CmbPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 220, 50));

        TxaObservaciones.setColumns(20);
        TxaObservaciones.setRows(5);
        TxaObservaciones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Observaciones"));
        jScrollPane1.setViewportView(TxaObservaciones);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 230, 110));

        CmbOrdenes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CmbOrdenes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Seleccione una orden"));
        add(CmbOrdenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 210, 50));

        BtnGuardar.setBackground(new java.awt.Color(180, 205, 235));
        BtnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        BtnGuardar.setText("Guardar");
        BtnGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtnGuardar.addActionListener(this::BtnGuardarActionPerformed);
        add(BtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 110, 30));

        BtnCrearOrden.setBackground(new java.awt.Color(180, 205, 235));
        BtnCrearOrden.setText("Crear Orden");
        BtnCrearOrden.addActionListener(this::BtnCrearOrdenActionPerformed);
        add(BtnCrearOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        CmbEspecialidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CmbEspecialidades.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Seleccione una especialidad"));
        add(CmbEspecialidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 210, 50));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Recuerda que para poder crear una   nueva consulta, el paciente debe        tener una orden ya registrada");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jScrollPane2.setViewportView(jTextArea1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 250, 110));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Crear consulta");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    //Boton de guardar nueva consulta
    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        boolean resultado = cont.ValidarOrdenes(CmbPacientes, CmbOrdenes);
        
        //Validamos que la consulta se haya creado y volvemos a cargar la tabla
        if(resultado){
            String obs = TxaObservaciones.getText();
            cont.agregarConsulta(CmbPacientes, CmbCie10, obs, CmbOrdenes, CmbEspecialidades);
            javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
            panelConsultas.cargarConsultas();
        }
    }//GEN-LAST:event_BtnGuardarActionPerformed

    //Boton para crear una nueva orden desde la consulta
    private void BtnCrearOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearOrdenActionPerformed
        JDialog dialog = new JDialog(
            SwingUtilities.getWindowAncestor(this),
            "Crear Orden",
            Dialog.ModalityType.APPLICATION_MODAL
        );
        dialog.setContentPane(new CrearOrden(panelOrdenes)); 
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);

        back.cargarOrdenes(CmbOrdenes);                                     
    }//GEN-LAST:event_BtnCrearOrdenActionPerformed

    private void CmbCie10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbCie10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbCie10ActionPerformed

    //Hacemos que el JComboBox de Cie10 cargue los registros que coincidan con la busqueda
    public void activarBuscador() {
        JComboBox<String> combo = CmbCie10;
        JTextField editor = (JTextField) combo.getEditor().getEditorComponent();
        Cargador cont = new Cargador();
        
        //Cada vez que el usuario de enter carguen las opciones
        editor.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    String texto = editor.getText().trim();
                    if (texto.length() < 2) {
                        System.out.println("Debe digitar mínimo 2 caracteres");
                        return;
                    }
                    cont.cargarCie10(combo, texto);
                    combo.showPopup();
                    editor.setCaretPosition(editor.getText().length());
                }
            }
        });
    }
    
    //Cargamos las opciones de cada JComboBox
    public void cargarOpciones(){        
        back.cargarPacientes(CmbPacientes);
        back.cargarOrdenes(CmbOrdenes);
        back.cargarServicios(CmbEspecialidades);
    }
    
    //Ponemos los JComboBox blancos para que no rompa el diseño
    private void ponerComboBlanco(javax.swing.JComboBox<String> combo) {
        combo.setBackground(Color.WHITE);
        combo.setForeground(Color.BLACK);
        combo.setOpaque(true); // importante para que se vea el fondo

        combo.setRenderer(new javax.swing.plaf.basic.BasicComboBoxRenderer() {
            @Override
            public java.awt.Component getListCellRendererComponent(JList<?> list, Object value,
                    int index, boolean isSelected, boolean cellHasFocus) {
                java.awt.Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (isSelected) {
                    c.setBackground(new Color(30, 144, 255)); // azul para el seleccionado
                    c.setForeground(Color.WHITE);
                } else {
                    c.setBackground(Color.WHITE); // fondo blanco siempre
                    c.setForeground(Color.BLACK);
                }
                return c;
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCrearOrden;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JComboBox<String> CmbCie10;
    private javax.swing.JComboBox<String> CmbEspecialidades;
    private javax.swing.JComboBox<String> CmbOrdenes;
    private javax.swing.JComboBox<String> CmbPacientes;
    private javax.swing.JTextArea TxaObservaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
