/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package System.JPanels;

import Backend.Cargador;
import Controller.Controlador;
import java.awt.Color;
import javax.swing.JList;
/**
 *
 * @author Miguel Angel
 * 
 * Interfaz que muestra el formulario de crear orden
 * 
 */

public class CrearOrden extends javax.swing.JPanel {
    private Ordenes panelOrdenes;
    /**
     * Creates new form CrearOrden
     */
    public CrearOrden(Ordenes panelOrdenes) {
        this.panelOrdenes = panelOrdenes;
        initComponents();
        cargarOpciones();
        
        //Ponemos los JComboBox blancos para que no rompa el diseño
        ponerComboBlanco(CmbPacie);
        ponerComboBlanco(CmbEstado);
        ponerComboBlanco(CmbServicios);
        ponerComboBlanco(CmbTipos);
       
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CmbPacie = new javax.swing.JComboBox<>();
        CmbServicios = new javax.swing.JComboBox<>();
        CmbTipos = new javax.swing.JComboBox<>();
        CmbEstado = new javax.swing.JComboBox<>();
        BtnCrearOrden = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel() {
            java.util.List<java.awt.Point> puntos = new java.util.ArrayList<>();

            {
                // Bloque de inicialización
                java.awt.event.MouseAdapter mouse = new java.awt.event.MouseAdapter() {
                    @Override
                    public void mousePressed(java.awt.event.MouseEvent e) {
                        puntos.add(e.getPoint());
                        repaint();
                    }

                    @Override
                    public void mouseDragged(java.awt.event.MouseEvent e) {
                        puntos.add(e.getPoint());
                        repaint();
                    }
                };
                addMouseListener(mouse);
                addMouseMotionListener(mouse);
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
                g2.setColor(java.awt.Color.BLACK);
                g2.setStroke(new java.awt.BasicStroke(2f));

                for (int i = 1; i < puntos.size(); i++) {
                    java.awt.Point p1 = puntos.get(i - 1);
                    java.awt.Point p2 = puntos.get(i);
                    g2.drawLine(p1.x, p1.y, p2.x, p2.y);
                }
            }

            public void limpiar() {
                puntos.clear();
                repaint();
            }
        };
        ;

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setPreferredSize(new java.awt.Dimension(600, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Crear orden");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        CmbPacie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CmbPacie.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Seleccione un paciente"));
        CmbPacie.setOpaque(true);
        add(CmbPacie, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 240, 49));

        CmbServicios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CmbServicios.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Seleccione un servicio"));
        add(CmbServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 240, 50));

        CmbTipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CmbTipos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Seleccione un tipo de orden"));
        add(CmbTipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 240, 50));

        CmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CmbEstado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Seleccione el estado de la orden"));
        add(CmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 240, 50));

        BtnCrearOrden.setBackground(new java.awt.Color(180, 205, 235));
        BtnCrearOrden.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnCrearOrden.setText("Crear");
        BtnCrearOrden.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtnCrearOrden.addActionListener(this::BtnCrearOrdenActionPerformed);
        add(BtnCrearOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 100, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Firma"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    //Boton de crear orden
    private void BtnCrearOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearOrdenActionPerformed
        Controlador cont = new Controlador();
        cont.agregarOrden(CmbPacie, CmbServicios, CmbTipos, CmbEstado);
        javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
        panelOrdenes.cargarOrdenes();
        
    }//GEN-LAST:event_BtnCrearOrdenActionPerformed

    //Cargamos las opciones para cada JComboBox
    public void cargarOpciones(){
        Cargador back = new Cargador();
        back.cargarPacientes(CmbPacie);
        back.cargarServicios(CmbServicios);
        back.cargarTipos(CmbTipos);
        back.cargarEstados(CmbEstado);
    }
    
    //Ponemos los JComboBox blancos para que no rompa el diseño
    private void ponerComboBlanco(javax.swing.JComboBox<String> combo) {
        combo.setBackground(Color.WHITE);
        combo.setForeground(Color.BLACK);
        combo.setOpaque(true); // importante para que se vea el fondo

        combo.setRenderer(new javax.swing.plaf.basic.BasicComboBoxRenderer() {
            @Override
            public java.awt.Component getListCellRendererComponent(JList<?> list, Object value,
                    int index, boolean isSelected, boolean cellHasFocus) {
                java.awt.Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (isSelected) {
                    c.setBackground(new Color(30, 144, 255)); // azul para el seleccionado
                    c.setForeground(Color.WHITE);
                } else {
                    c.setBackground(Color.WHITE); // fondo blanco siempre
                    c.setForeground(Color.BLACK);
                }
                return c;
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCrearOrden;
    private javax.swing.JComboBox<String> CmbEstado;
    private javax.swing.JComboBox<String> CmbPacie;
    private javax.swing.JComboBox<String> CmbServicios;
    private javax.swing.JComboBox<String> CmbTipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
