/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package System.JPanels;

import java.awt.Color;

/**
 *
 * @author Juan David
 * 
 * Interfaz que muestra resumen de el sistema
 * usuarios registrados, pacientes, ordenes, consultas, etc
 * 
 */

public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        cargarDashboard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        cardUsuarios = new javax.swing.JPanel();
        cardPacientes = new javax.swing.JPanel();
        cardHistorias = new javax.swing.JPanel();
        cardOrdenes = new javax.swing.JPanel();
        cardRemisiones = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Dashboard");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 36, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 650, 230));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 102, 689, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/medicine_9410386.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 6, 72, 78));

        cardUsuarios.setBackground(new java.awt.Color(255, 255, 102));
        cardUsuarios.setPreferredSize(new java.awt.Dimension(200, 130));

        javax.swing.GroupLayout cardUsuariosLayout = new javax.swing.GroupLayout(cardUsuarios);
        cardUsuarios.setLayout(cardUsuariosLayout);
        cardUsuariosLayout.setHorizontalGroup(
            cardUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        cardUsuariosLayout.setVerticalGroup(
            cardUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(cardUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 130));

        cardPacientes.setBackground(new java.awt.Color(255, 255, 102));
        cardPacientes.setPreferredSize(new java.awt.Dimension(200, 130));

        javax.swing.GroupLayout cardPacientesLayout = new javax.swing.GroupLayout(cardPacientes);
        cardPacientes.setLayout(cardPacientesLayout);
        cardPacientesLayout.setHorizontalGroup(
            cardPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        cardPacientesLayout.setVerticalGroup(
            cardPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        add(cardPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        cardHistorias.setBackground(new java.awt.Color(255, 255, 102));
        cardHistorias.setMinimumSize(new java.awt.Dimension(200, 130));
        cardHistorias.setPreferredSize(new java.awt.Dimension(200, 130));

        javax.swing.GroupLayout cardHistoriasLayout = new javax.swing.GroupLayout(cardHistorias);
        cardHistorias.setLayout(cardHistoriasLayout);
        cardHistoriasLayout.setHorizontalGroup(
            cardHistoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        cardHistoriasLayout.setVerticalGroup(
            cardHistoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        add(cardHistorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 200, 130));

        cardOrdenes.setBackground(new java.awt.Color(255, 255, 102));
        cardOrdenes.setPreferredSize(new java.awt.Dimension(200, 130));

        javax.swing.GroupLayout cardOrdenesLayout = new javax.swing.GroupLayout(cardOrdenes);
        cardOrdenes.setLayout(cardOrdenesLayout);
        cardOrdenesLayout.setHorizontalGroup(
            cardOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        cardOrdenesLayout.setVerticalGroup(
            cardOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        add(cardOrdenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        cardRemisiones.setBackground(new java.awt.Color(255, 255, 102));
        cardRemisiones.setPreferredSize(new java.awt.Dimension(200, 130));

        javax.swing.GroupLayout cardRemisionesLayout = new javax.swing.GroupLayout(cardRemisiones);
        cardRemisiones.setLayout(cardRemisionesLayout);
        cardRemisionesLayout.setHorizontalGroup(
            cardRemisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        cardRemisionesLayout.setVerticalGroup(
            cardRemisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        add(cardRemisiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    //Cargamos las tarjetas de cada modulo
    public void cargarDashboard() {
        Controller.Controlador cont = new Controller.Controlador();

        //Contamos la cantidad de elementos que hay en la base
        int usuarios = cont.contarUsuarios();
        int pacientes = cont.contarPacientes();
        int historias = cont.contarHistorias();
        int ordenes = cont.contarOrdenes();
        int remisiones = cont.contarRemisiones();

        // Cambiar layout para que el Card se pueda mostrar
        cardUsuarios.setLayout(new java.awt.BorderLayout());
        cardPacientes.setLayout(new java.awt.BorderLayout());
        cardHistorias.setLayout(new java.awt.BorderLayout());
        cardOrdenes.setLayout(new java.awt.BorderLayout());
        cardRemisiones.setLayout(new java.awt.BorderLayout());

        // Limpiar paneles
        cardUsuarios.removeAll();
        cardPacientes.removeAll();
        cardHistorias.removeAll();
        cardOrdenes.removeAll();
        cardRemisiones.removeAll();

        // Crear Cards
        Card cUsuarios = new Card("Usuarios", String.valueOf(usuarios), new Color(180, 205, 235));     // azul muy oscuro
        Card cPacientes = new Card("Pacientes", String.valueOf(pacientes), new Color(180, 205, 235)); // azul intermedio
        Card cHistorias = new Card("Historias Clínicas", String.valueOf(historias), new Color(180, 205, 235)); // azul suave
        Card cOrdenes = new Card("Órdenes", String.valueOf(ordenes), new Color(180, 205, 235)); // azul pastel
        Card cRemisiones = new Card("Remisiones", String.valueOf(remisiones), new Color(180, 205, 235)); // azul muy claro


        // Agregar dentro de los paneles existentes
        cardUsuarios.add(cUsuarios);
        cardPacientes.add(cPacientes);
        cardHistorias.add(cHistorias);
        cardOrdenes.add(cOrdenes);
        cardRemisiones.add(cRemisiones);

        // Refrescar
        revalidate();
        repaint();

        // Cargar tabla
        jTable1.setModel(cont.consultasPorEspecialidad());
        diseñoTabla();
    }
    
    //Ajustamos el diseño de la tabla
    public void diseñoTabla(){
        // Estilo de la tabla
        jTable1.setRowHeight(28);
        jTable1.setShowGrid(false);
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jTable1.setForeground(new Color(30, 30, 30));

        // Encabezado
        jTable1.getTableHeader().setFont(new java.awt.Font("Segoe UI", 1, 14));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(40, 70, 120)); // azul oscuro
        jTable1.getTableHeader().setForeground(Color.WHITE);

        // Zebra azul suave
        jTable1.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(
                javax.swing.JTable table, Object value, boolean isSelected,
                boolean hasFocus, int row, int column
            ) {
                java.awt.Component c = super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column
                );

                if (!isSelected) {
                    if (row % 2 == 0) {
                        c.setBackground(new Color(235, 245, 255)); // azul muy claro
                    } else {
                        c.setBackground(Color.WHITE);
                    }
                } else {
                    c.setBackground(new Color(180, 205, 235)); // azul de selección
                }
                return c;
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardHistorias;
    private javax.swing.JPanel cardOrdenes;
    private javax.swing.JPanel cardPacientes;
    private javax.swing.JPanel cardRemisiones;
    private javax.swing.JPanel cardUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
