/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package System.JPanels;

import Backend.Cargador;
import Controller.Controlador;

/**
 *
 * @author Sebastian
 * 
 * Interfaz que muestra las historias clinicas que son el
 * conjunto de ordenes y consultas de un paciente
 * 
 */

public class HistoriasClinicas extends javax.swing.JPanel {

    /**
     * Creates new form HistoriasClinicas
     */
    public HistoriasClinicas() {
        initComponents();
        cargarOpciones();
        aplicarEstilos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TppHistorias = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblOrdenes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblConsultas = new javax.swing.JTable();
        LblNumeroHistoria = new javax.swing.JLabel();
        BtnBuscar = new javax.swing.JButton();
        CmbPacientes = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TblOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cod. Servicio", "Usuario Creador", "Doc. Usuario", "Tipo", "Estado", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblOrdenes);

        TppHistorias.addTab("Ordenes", jScrollPane1);

        TblConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Enfermedad", "Observaciones", "N° Orden", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TblConsultas);

        TppHistorias.addTab("Consultas", jScrollPane2);

        add(TppHistorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 563, 424));

        LblNumeroHistoria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblNumeroHistoria.setText("Historia Clinica N°: ");
        add(LblNumeroHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 570, 50));

        BtnBuscar.setBackground(new java.awt.Color(180, 205, 235));
        BtnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(this::BtnBuscarActionPerformed);
        add(BtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        CmbPacientes.setBackground(new java.awt.Color(242, 242, 242));
        CmbPacientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CmbPacientes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Seleccione un paciente"));
        CmbPacientes.addActionListener(this::CmbPacientesActionPerformed);
        add(CmbPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 320, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void CmbPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbPacientesActionPerformed
        
    }//GEN-LAST:event_CmbPacientesActionPerformed

    //Boton de buscar paciente por documento
    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        Controlador cont = new Controlador();
        String[] seleccionado = cont.cargarOrdenesPorDocumento(CmbPacientes, TblOrdenes);
        cont.cargarConsultasPorDocumento(CmbPacientes, TblConsultas);
        
        //Mostramos nombre y documento del usuario seleccionado
        LblNumeroHistoria.setText("Historia Clínica de: " + seleccionado[0] + " - " + seleccionado[1]);
    }//GEN-LAST:event_BtnBuscarActionPerformed

    //Cargamos las opciones para los JComboBox
    public void cargarOpciones(){
        Cargador back = new Cargador();
        back.cargarPacientes(CmbPacientes);
    }
    
    //Aplicamos estilos al JTabbedPane
    public void aplicarEstilos() {

        //  Estilo de los Tabs (JTabbedPane) 
        TppHistorias.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        TppHistorias.setBackground(new java.awt.Color(245, 245, 245));
        TppHistorias.setForeground(new java.awt.Color(40, 40, 40));

        //  Estilo para ScrollPane de Consultas 
        estilizarScroll(jScrollPane2);
        estilizarTabla(TblConsultas);

        //  Estilo para ScrollPane de Ordenes 
        estilizarScroll(jScrollPane1);
        estilizarTabla(TblOrdenes);
    }

    //Aplicamos estilos al JTabbedPane
    private void estilizarScroll(javax.swing.JScrollPane scroll) {
        scroll.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        scroll.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1, true));
        scroll.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }

    //Aplicamos estilos al JTabbedPane
    private void estilizarTabla(javax.swing.JTable tabla) {

        tabla.setAutoCreateRowSorter(true);

        // Encabezado
        tabla.getTableHeader().setOpaque(false);
        tabla.getTableHeader().setBackground(new java.awt.Color(30, 30, 30));
        tabla.getTableHeader().setForeground(java.awt.Color.WHITE);
        tabla.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

        // Filas
        tabla.setRowHeight(30);
        tabla.setShowHorizontalLines(true);
        tabla.setShowVerticalLines(false);
        tabla.setGridColor(new java.awt.Color(220, 220, 220));
        tabla.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));

        // Zebra + color seleccionado
        tabla.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table,
                    Object value, boolean isSelected, boolean hasFocus, int row, int column) {

                java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                c.setForeground(java.awt.Color.BLACK);

                if (isSelected) {
                    c.setBackground(new java.awt.Color(30, 144, 255)); // Azul suave
                    c.setForeground(java.awt.Color.WHITE);
                } else {
                    c.setBackground(row % 2 == 0
                            ? new java.awt.Color(245, 245, 245)
                            : java.awt.Color.WHITE);
                }

                return c;
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JComboBox<String> CmbPacientes;
    private javax.swing.JLabel LblNumeroHistoria;
    private javax.swing.JTable TblConsultas;
    private javax.swing.JTable TblOrdenes;
    private javax.swing.JTabbedPane TppHistorias;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
