/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package System.JPanels;

import Backend.ButtonEditor;
import Backend.ButtonRenderer;
import Backend.DatosOrden;
import Controller.Controlador;
import com.itextpdf.text.pdf.AcroFields;
import com.itextpdf.text.pdf.PdfReader;
import com.itextpdf.text.pdf.PdfStamper;
import java.awt.Dialog;
import java.io.FileOutputStream;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Miguel Angel
 * 
 * Interfaz que muestra una tabla con los datos de las ordenes
 * registradas en el sistema
 * 
 */
public class Ordenes extends javax.swing.JPanel {

    /**
     * Creates new form Ordenes
     */
    public Ordenes() {
        initComponents();
        cargarOrdenes();
        diseño();
        
        //Definimos el placeholder del filtro de busqueda
        agregarPlaceholder(TxtBuscar, "Buscar orden...");
        TxtBuscar.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) { filtrar(); }
            @Override
            public void removeUpdate(DocumentEvent e) { filtrar(); }
            @Override
            public void changedUpdate(DocumentEvent e) { filtrar(); }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblOrdenes = new javax.swing.JTable();
        BtnCrear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TxtBuscar = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Ordenes");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 113, 25));

        TblOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Fecha y Hora", "Nombre", "Documento", "Cod. Serv", "Nom. Serv", "Nom. Creador", "Cargo", "Tipo", "Estado", "PDF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblOrdenes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(TblOrdenes);
        TblOrdenes.getAccessibleContext().setAccessibleParent(TblOrdenes);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 688, -1));

        BtnCrear.setBackground(new java.awt.Color(180, 205, 235));
        BtnCrear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnCrear.setText("Crear");
        BtnCrear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtnCrear.addActionListener(this::BtnCrearActionPerformed);
        add(BtnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 80, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/medicine_9410386.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));
        add(TxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 142, 130, 20));
    }// </editor-fold>//GEN-END:initComponents

    //Boton de crear nueva orden
    private void BtnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearActionPerformed
    JDialog dialog = new JDialog(
            SwingUtilities.getWindowAncestor(this),
            "Crear Orden",
            Dialog.ModalityType.APPLICATION_MODAL
        );
        dialog.setContentPane(new CrearOrden(this)); 
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);  
    }//GEN-LAST:event_BtnCrearActionPerformed
    
    //Cargamos las ordenes registradas en la base de datos y las pone en una tabla
    public void cargarOrdenes(){
        Controlador cont = new Controlador();
        cont.cargarOrdenes(TblOrdenes);
        
        //Agregamos el boton de descargar PDF
        TblOrdenes.getColumnModel().getColumn(10).setCellRenderer(new ButtonRenderer());
        TblOrdenes.getColumnModel().getColumn(10)
            .setCellEditor(new ButtonEditor(new JTextField(), id -> {
                generarPDF(id);
        }));


    }
    
    //Generamos el pdf con los datos de la orden seleccionada
    public void generarPDF(int idOrden) {

        //Obtenemos los datos de la orden
        Controlador cont = new Controlador();
        DatosOrden datos = cont.obtenerDatosOrden(idOrden);

        try {
            //Cargamos la plantilla
            String plantilla = "src\\main\\resources\\Plantillas\\orden_base_template.pdf";

            //Nombre del archivo final
            String salida = "Orden_" + idOrden + ".pdf";
            
            String orden = String.valueOf(idOrden);

            //Leemos la plantilla
            PdfReader reader = new PdfReader(plantilla);
            PdfStamper stamper = new PdfStamper(reader, new FileOutputStream(salida));
            AcroFields form = stamper.getAcroFields();

            //Llenamos la plantilla con los datos de la orden
            form.setField("txtFecha", datos.fechaHora);
            form.setField("txtNombrePaciente", datos.nombrePaciente);
            form.setField("txtDocumento", datos.documento);
            form.setField("txtidOrden", orden);
            form.setField("txtServicio", datos.nombreServicio);
            form.setField("txtTipo", datos.tipo);
            form.setField("txtEstado", datos.estado);
            form.setField("txtUsuario", datos.nombreUsuario);
            form.setField("txtCargo", datos.cargo);

            //Ajustamos el PDF para que no se puedan editar los campos
            stamper.setFormFlattening(true);
            stamper.close();
            reader.close();

            JOptionPane.showMessageDialog(null, "Orden generada: " + salida);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error generando PDF: " + e.getMessage());
            e.printStackTrace();
        }
    }

    //Aplicamos diseño a la tabla de ordenes
    public void diseño(){
        // Diseño del encabezado
        TblOrdenes.setAutoCreateRowSorter(true);
        TblOrdenes.getTableHeader().setOpaque(false);
        TblOrdenes.getTableHeader().setBackground(new java.awt.Color(30, 30, 30));
        TblOrdenes.getTableHeader().setForeground(java.awt.Color.WHITE);
        TblOrdenes.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

        // Altura de filas
        TblOrdenes.setRowHeight(30);

        // Bordes y color de líneas
        TblOrdenes.setShowHorizontalLines(true);
        TblOrdenes.setShowVerticalLines(false);
        TblOrdenes.setGridColor(new java.awt.Color(220, 220, 220));

        // Fuente del contenido
        TblOrdenes.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));

        // Renderer para zebra rows + selección personalizada
        TblOrdenes.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table,
                    Object value, boolean isSelected, boolean hasFocus, int row, int column) {

                java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                // Color de texto normal
                c.setForeground(java.awt.Color.BLACK);

                if (isSelected) {
                    c.setBackground(new java.awt.Color(30, 144, 255)); // azul suave
                    c.setForeground(java.awt.Color.WHITE);
                } else {
                    // Zebra rows
                    c.setBackground(row % 2 == 0
                            ? new java.awt.Color(245, 245, 245)
                            : java.awt.Color.WHITE);
                }

                return c;
            }
        });

    }
    
    //Filtro de la tabla de ordenes
    private void filtrar() {
        String placeholder = "Buscar orden...";
        String texto = TxtBuscar.getText();
        if (texto == null) texto = "";

        DefaultTableModel model = (DefaultTableModel) TblOrdenes.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        TblOrdenes.setRowSorter(sorter);

        // Si está vacío o es el placeholder, quitamos el filtro
        if (texto.trim().isEmpty() || texto.equals(placeholder)) {
            sorter.setRowFilter(null); // Esto quita cualquier filtro y muestra todo
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto));
        }
    }

    //Le agregamos un placeholder al campo de filtro
    private void agregarPlaceholder(javax.swing.JTextField campo, String texto) {
        campo.setText(texto);
        campo.setForeground(new java.awt.Color(150, 150, 150));

        campo.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (campo.getText().equals(texto)) {
                    campo.setText("");
                    campo.setForeground(new java.awt.Color(0, 0, 0));
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (campo.getText().isEmpty()) {
                    campo.setText(texto);
                    campo.setForeground(new java.awt.Color(150, 150, 150));
                }
            }
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCrear;
    private javax.swing.JTable TblOrdenes;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
