/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package System.JPanels;

import BD.TPacientes;
import Backend.USesion;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Juan David
 * 
 * Interfaz que muestra todos los pacientes creados
 * en el sistema en una tabla
 * 
 */
public class Pacientes extends javax.swing.JPanel {

    /**
     * Creates new form Pacientes
     */
    public Pacientes() {
        initComponents();
        cargarPacientes();
        diseño();
        setPreferredSize(new Dimension(480, 520));
        
        //Damos estilos a los botones
        estiloBoton(BtnCrearPaciente);
        estiloBoton(BtnActualizar);
        
        //Agregamos un placeholder al filtro
        agregarPlaceholder(TxtBuscar, "Buscar paciente...");
        TxtBuscar.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) { filtrar(); }
            @Override
            public void removeUpdate(DocumentEvent e) { filtrar(); }
            @Override
            public void changedUpdate(DocumentEvent e) { filtrar(); }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TblPacientes = new javax.swing.JTable();
        BtnCrearPaciente = new javax.swing.JButton();
        BtnActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtBuscar = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(680, 530));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Documento", "Telefono", "Correo", "Direccion", "Edad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblPacientes);
        if (TblPacientes.getColumnModel().getColumnCount() > 0) {
            TblPacientes.getColumnModel().getColumn(0).setResizable(false);
            TblPacientes.getColumnModel().getColumn(1).setResizable(false);
            TblPacientes.getColumnModel().getColumn(2).setResizable(false);
            TblPacientes.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 710, 366));

        BtnCrearPaciente.setText("Registar Paciente");
        BtnCrearPaciente.addActionListener(this::BtnCrearPacienteActionPerformed);
        add(BtnCrearPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        BtnActualizar.setText("Actualizar Paciente");
        BtnActualizar.addActionListener(this::BtnActualizarActionPerformed);
        add(BtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Pacientes del sistema");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/medicine_9410386.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));
        add(TxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 130, 30));
    }// </editor-fold>//GEN-END:initComponents

    //Boton crear paciente
    private void BtnCrearPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearPacienteActionPerformed
        
        //Validamos que el usuario loggeado sea Admin para poder crear un nuevo paciente
        if(USesion.usuarioRol == 1){
            javax.swing.JFrame ventana = new javax.swing.JFrame("Registrar Paciente");
            ventana.setContentPane(new RegistrarPaciente(this));
            ventana.pack();
            ventana.setLocationRelativeTo(this);
            ventana.setVisible(true);
        }else{
            BtnCrearPaciente.setForeground(new java.awt.Color(120,120,120)); // Gris suave
            JOptionPane.showMessageDialog(this, "No tienes permisos para crear pacientes.","Acceso denegado",JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_BtnCrearPacienteActionPerformed

    //Boton actualizar paciente
    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed
        
        //Validamos que el usuario loggeado sea Admin para poder actualizar un nuevo paciente
        if(USesion.usuarioRol == 1){
            javax.swing.JFrame ventana = new javax.swing.JFrame("Actualizar Paciente");
            ventana.setContentPane(new ActualizarPaciente(this));
            ventana.pack();
            ventana.setLocationRelativeTo(this);
            ventana.setVisible(true);
        }else{
            BtnActualizar.setForeground(new java.awt.Color(120,120,120)); // Gris suave
            JOptionPane.showMessageDialog(this, "No tienes permisos para actualizar pacientes.","Acceso denegado",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_BtnActualizarActionPerformed

    //Cargamos todos los pacientes del sistema y los ponemos en una tabla
    public void cargarPacientes() {
        DefaultTableModel model = (DefaultTableModel) TblPacientes.getModel();
        model.setRowCount(0); // limpiar tabla

        TPacientes tpac = new TPacientes();
        List<Object[]> lista = tpac.obtenerPacientes();

        for (Object[] fila : lista) {
            model.addRow(fila);
        }
    }
    
    //Diseño de la tabla de pacientes
    public void diseño(){
        // Diseño del encabezado
        TblPacientes.setAutoCreateRowSorter(true);
        TblPacientes.getTableHeader().setOpaque(false);
        TblPacientes.getTableHeader().setBackground(new java.awt.Color(30, 30, 30));
        TblPacientes.getTableHeader().setForeground(java.awt.Color.WHITE);
        TblPacientes.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

        // Altura de filas
        TblPacientes.setRowHeight(30);

        // Bordes y color de líneas
        TblPacientes.setShowHorizontalLines(true);
        TblPacientes.setShowVerticalLines(false);
        TblPacientes.setGridColor(new java.awt.Color(220, 220, 220));

        // Fuente del contenido
        TblPacientes.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));

        // Renderer para filas, zebra rows, selección y centrado del texto
        javax.swing.table.DefaultTableCellRenderer renderer = new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(
                    javax.swing.JTable table, Object value, boolean isSelected,
                    boolean hasFocus, int row, int column) {

                java.awt.Component c = super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);

                // CENTRAR EL TEXTO
                setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

                // Color de texto normal
                c.setForeground(java.awt.Color.BLACK);

                if (isSelected) {
                    c.setBackground(new java.awt.Color(30, 144, 255)); // azul suave
                    c.setForeground(java.awt.Color.WHITE);
                } else {
                    // Zebra rows
                    c.setBackground(row % 2 == 0
                            ? new java.awt.Color(245, 245, 245)
                            : java.awt.Color.WHITE);
                }

                return c;
            }
        };

        // Aplicamos el renderer como predeterminado para toda la tabla
        TblPacientes.setDefaultRenderer(Object.class, renderer);
    }

    
    //Estilos para los botones
    private void estiloBoton(javax.swing.JButton btn) {
        btn.setFocusPainted(false);
        btn.setBorderPainted(false);

        // Fondo suave gris claro
        btn.setBackground(new java.awt.Color(180, 205, 235));

        // Texto gris oscuro
        btn.setForeground(new java.awt.Color(0, 0, 0));

        btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));



      
    }
    
    //Filtro de la tabla de pacientes
    private void filtrar() {
        String placeholder = "Buscar paciente...";
        String texto = TxtBuscar.getText();
        if (texto == null) texto = "";

        DefaultTableModel model = (DefaultTableModel) TblPacientes.getModel();

        // Obtenemos el sorter actual (si existe)
        TableRowSorter<DefaultTableModel> sorter = null;
        if (TblPacientes.getRowSorter() instanceof TableRowSorter) {
            sorter = (TableRowSorter<DefaultTableModel>) TblPacientes.getRowSorter();
        }

        // Si está vacío o es el placeholder -> quitamos cualquier filtro y devolvemos todos los registros
        if (texto.trim().isEmpty() || texto.equals(placeholder)) {
            if (sorter != null) {
                sorter.setRowFilter(null);         // deja visible todo
            } else {
                TblPacientes.setRowSorter(null);   // no hay sorter: asegurar que no haya filtro
            }
            return;
        }

        // Si no hay sorter, creamos uno nuevo
        if (sorter == null) {
            sorter = new TableRowSorter<>(model);
            TblPacientes.setRowSorter(sorter);
        }

        // Aplicamos filtro (case-insensitive). Usamos Pattern.quote para escapar el texto del usuario.
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + java.util.regex.Pattern.quote(texto)));
    }

    
    //Le agregamos un placeholder al campo de filtro
    private void agregarPlaceholder(javax.swing.JTextField campo, String texto) {
        campo.setText(texto);
        campo.setForeground(new java.awt.Color(150, 150, 150));

        campo.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (campo.getText().equals(texto)) {
                    campo.setText("");
                    campo.setForeground(new java.awt.Color(0, 0, 0));
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (campo.getText().isEmpty()) {
                    campo.setText(texto);
                    campo.setForeground(new java.awt.Color(150, 150, 150));
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnCrearPaciente;
    private javax.swing.JTable TblPacientes;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
