/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package System.JPanels;


import Controller.Controlador;

/**
 *
 * @author Miguel Angel
 * 
 * Interfaz que muestra el formulario para crear un 
 * nuevo paciente
 * 
 */
public class RegistrarPaciente extends javax.swing.JPanel {
    private Pacientes panelPacientes;
    /**
     * Creates new form RegistrarUsuario
     */
    public RegistrarPaciente(Pacientes panelPacientes) {
        this.panelPacientes = panelPacientes;
        initComponents();
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); 
        jLabel1.setForeground(new java.awt.Color(70, 70, 70));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxfDocumento = new javax.swing.JTextField();
        TflNombre = new javax.swing.JTextField();
        TxfTelefono = new javax.swing.JTextField();
        TxfCorreo = new javax.swing.JTextField();
        TxfDireccion = new javax.swing.JTextField();
        BtnCrear = new javax.swing.JButton();
        TxfEdad = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setPreferredSize(new java.awt.Dimension(600, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Registrar paciente");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, 40));

        TxfDocumento.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Documento: "));
        add(TxfDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 230, -1));

        TflNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nombre: "));
        add(TflNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 230, -1));

        TxfTelefono.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Telefono: "));
        add(TxfTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 230, -1));

        TxfCorreo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Correo:"));
        add(TxfCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 250, -1));

        TxfDireccion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dirrecion:"));
        TxfDireccion.addActionListener(this::TxfDireccionActionPerformed);
        add(TxfDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 250, -1));

        BtnCrear.setBackground(new java.awt.Color(180, 205, 235));
        BtnCrear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnCrear.setText("Crear");
        BtnCrear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtnCrear.addActionListener(this::BtnCrearActionPerformed);
        add(BtnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 100, 30));

        TxfEdad.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Edad: "));
        TxfEdad.addActionListener(this::TxfEdadActionPerformed);
        add(TxfEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 250, -1));
    }// </editor-fold>//GEN-END:initComponents

    //Boton crear paciente
    private void BtnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearActionPerformed
    Controlador cont = new Controlador();
    cont.AgregarPaciente(TflNombre, TxfTelefono, TxfEdad, TxfDocumento, TxfCorreo, TxfDireccion);

    // cerrar ventana
    javax.swing.SwingUtilities.getWindowAncestor(this).dispose();

    // refrescar tabla
    panelPacientes.cargarPacientes();
    }//GEN-LAST:event_BtnCrearActionPerformed

    private void TxfDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxfDireccionActionPerformed

    private void TxfEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxfEdadActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCrear;
    private javax.swing.JTextField TflNombre;
    private javax.swing.JTextField TxfCorreo;
    private javax.swing.JTextField TxfDireccion;
    private javax.swing.JTextField TxfDocumento;
    private javax.swing.JTextField TxfEdad;
    private javax.swing.JTextField TxfTelefono;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
