/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package System.JPanels;

import BD.TUsuarios;
import java.sql.ResultSet;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Sebastian
 * 
 * Interfaz que muestra los usuarios registrados
 * en el sistema
 * 
 */
public class Usuarios extends javax.swing.JPanel {

    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
        diseño();
        cargarUsuarios();
        
        //Filtro de la tabla de consultas
        agregarPlaceholder(TxtBuscar, "Buscar usuario...");
        TxtBuscar.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) { filtrar(); }
            @Override
            public void removeUpdate(DocumentEvent e) { filtrar(); }
            @Override
            public void changedUpdate(DocumentEvent e) { filtrar(); }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TblUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtBuscar = new javax.swing.JTextField();

        setBackground(new java.awt.Color(225, 225, 225));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(725, 670));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Telefono", "Edad", "Documento", "Rol", "Especialidad", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblUsuarios);
        if (TblUsuarios.getColumnModel().getColumnCount() > 0) {
            TblUsuarios.getColumnModel().getColumn(0).setResizable(false);
            TblUsuarios.getColumnModel().getColumn(1).setResizable(false);
            TblUsuarios.getColumnModel().getColumn(2).setResizable(false);
            TblUsuarios.getColumnModel().getColumn(3).setResizable(false);
            TblUsuarios.getColumnModel().getColumn(4).setResizable(false);
            TblUsuarios.getColumnModel().getColumn(5).setResizable(false);
            TblUsuarios.getColumnModel().getColumn(6).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 700, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Usuarios del sistema");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/medicine_9410386.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 70, 70));
        add(TxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 160, 30));
    }// </editor-fold>//GEN-END:initComponents

    //Cargamos los usurios registrados en el sistema y los ponemos en una tabla
    private void cargarUsuarios() {
        DefaultTableModel model = (DefaultTableModel) TblUsuarios.getModel();
        model.setRowCount(0); // limpiar tabla

        TUsuarios tuser = new TUsuarios();
        ResultSet rs = tuser.obtenerUsuarios();

        try {
            while (rs != null && rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("Nombre"),
                    rs.getString("Telefono"),
                    rs.getInt("Edad"),
                    rs.getString("Documento"),
                    rs.getString("Rol"),   // CORRECTO
                    rs.getString("Especialidad") == null ? "N/A" : rs.getString("Especialidad"), // CORRECTO
                    rs.getString("Email")
                });
            }
        } catch (Exception e) {
            System.out.println("Error al cargar usuarios: " + e.getMessage());
        }
    }
    
    //Diseño de la tabla de usuarios
    public void diseño(){
        // Diseño del encabezado
        
        TblUsuarios.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseMoved(java.awt.event.MouseEvent e) {
                int row = TblUsuarios.rowAtPoint(e.getPoint());
                TblUsuarios.setRowSelectionInterval(row, row);
            }
        });

        jScrollPane1.getViewport().setBackground(new java.awt.Color(255,255,255));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200,200,200),1,true));
        TblUsuarios.setAutoCreateRowSorter(true);
        TblUsuarios.getTableHeader().setOpaque(false);
        TblUsuarios.getTableHeader().setBackground(new java.awt.Color(30, 30, 30));
        TblUsuarios.getTableHeader().setForeground(java.awt.Color.WHITE);
        TblUsuarios.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

        // Altura de filas
        TblUsuarios.setRowHeight(30);

        // Bordes y color de líneas
        TblUsuarios.setShowHorizontalLines(true);
        TblUsuarios.setShowVerticalLines(false);
        TblUsuarios.setGridColor(new java.awt.Color(220, 220, 220));

        // Fuente del contenido
        TblUsuarios.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));

        // Renderer para zebra rows + selección personalizada
        TblUsuarios.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table,
                    Object value, boolean isSelected, boolean hasFocus, int row, int column) {

                java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                // Color de texto normal
                c.setForeground(java.awt.Color.BLACK);

                if (isSelected) {
                    c.setBackground(new java.awt.Color(30, 144, 255)); // azul suave
                    c.setForeground(java.awt.Color.WHITE);
                } else {
                    // Zebra rows
                    c.setBackground(row % 2 == 0
                            ? new java.awt.Color(245, 245, 245)
                            : java.awt.Color.WHITE);
                }

                return c;
            }
        });

    }
    
    //Filtro de la tabla de usuarios
    private void filtrar() {
        String placeholder = "Buscar usuario...";
        String texto = TxtBuscar.getText();
        if (texto == null) texto = "";

        // Si está vacío o es el placeholder, quitamos el filtro
        if (texto.trim().isEmpty() || texto.equals(placeholder)) { 
            return;
        }
        DefaultTableModel model = (DefaultTableModel) TblUsuarios.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        TblUsuarios.setRowSorter(sorter);

        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + TxtBuscar.getText()));
    }

    //Le agregamos un placeholder al campo de filtro
    private void agregarPlaceholder(javax.swing.JTextField campo, String texto) {
        campo.setText(texto);
        campo.setForeground(new java.awt.Color(150, 150, 150));

        campo.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (campo.getText().equals(texto)) {
                    campo.setText("");
                    campo.setForeground(new java.awt.Color(0, 0, 0));
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (campo.getText().isEmpty()) {
                    campo.setText(texto);
                    campo.setForeground(new java.awt.Color(150, 150, 150));
                }
            }
        });
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblUsuarios;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
