/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package System;

import Backend.USesion;
import System.JPanels.Consultas;
import System.JPanels.Dashboard;
import System.JPanels.HistoriasClinicas;
import System.JPanels.Ordenes;
import System.JPanels.Pacientes;
import System.JPanels.Usuarios;
import java.awt.CardLayout;
import javax.swing.JOptionPane;


/**
 *
 * @author Juan David
 * 
 * Este interfaz se encarga de mostrar las diferentes
 * secciones del sistema
 * 
 */


public class Home extends javax.swing.JFrame {
    private Ordenes panelOrdenes;
    private Consultas panelConsultas;
    private CardLayout cardLayout;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Home.class.getName());

    //Constructor y llamado de metodos
    public Home() {
        initComponents();
        //Mostramos el nombre del usuario loggeado
        JlbUser.setText("Bienvenido " + USesion.usuarioNombre);
        setLocationRelativeTo(null);
        cargarPaneles();
        iniciarReloj();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PnlOpciones = new javax.swing.JPanel();
        BtnUsuarios = new javax.swing.JButton();
        BtnPacientes = new javax.swing.JButton();
        JlbUser = new javax.swing.JLabel();
        BtnOrden = new javax.swing.JButton();
        BtnConsultas = new javax.swing.JButton();
        BtnHistorias = new javax.swing.JButton();
        LblHora = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BtnUsuarios1 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        PnlContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));

        PnlOpciones.setBackground(new java.awt.Color(255, 255, 255));

        BtnUsuarios.setFont(new java.awt.Font("Sans Serif Collection", 0, 22)); // NOI18N
        BtnUsuarios.setText("Usuarios");
        BtnUsuarios.setBorder(null);
        BtnUsuarios.setContentAreaFilled(false);
        BtnUsuarios.addActionListener(this::BtnUsuariosActionPerformed);

        BtnPacientes.setFont(new java.awt.Font("Sans Serif Collection", 0, 22)); // NOI18N
        BtnPacientes.setText("Pacientes");
        BtnPacientes.setBorder(null);
        BtnPacientes.setContentAreaFilled(false);
        BtnPacientes.addActionListener(this::BtnPacientesActionPerformed);

        JlbUser.setBackground(new java.awt.Color(255, 255, 255));
        JlbUser.setFont(new java.awt.Font("Sans Serif Collection", 1, 18)); // NOI18N

        BtnOrden.setFont(new java.awt.Font("Sans Serif Collection", 0, 22)); // NOI18N
        BtnOrden.setText("Ordenes");
        BtnOrden.setBorder(null);
        BtnOrden.setContentAreaFilled(false);
        BtnOrden.addActionListener(this::BtnOrdenActionPerformed);

        BtnConsultas.setFont(new java.awt.Font("Sans Serif Collection", 0, 22)); // NOI18N
        BtnConsultas.setText("Consultas");
        BtnConsultas.setBorder(null);
        BtnConsultas.setContentAreaFilled(false);
        BtnConsultas.addActionListener(this::BtnConsultasActionPerformed);

        BtnHistorias.setFont(new java.awt.Font("Sans Serif Collection", 0, 22)); // NOI18N
        BtnHistorias.setText("Historias");
        BtnHistorias.setBorder(null);
        BtnHistorias.setContentAreaFilled(false);
        BtnHistorias.addActionListener(this::BtnHistoriasActionPerformed);

        LblHora.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sick-person (1).png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/shopping-list (1).png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/find (1) (1).png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/file (1).png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/doctor (1).png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hogar (1).png"))); // NOI18N

        BtnUsuarios1.setFont(new java.awt.Font("Sans Serif Collection", 0, 22)); // NOI18N
        BtnUsuarios1.setText("Inicio");
        BtnUsuarios1.setBorder(null);
        BtnUsuarios1.setContentAreaFilled(false);
        BtnUsuarios1.addActionListener(this::BtnUsuarios1ActionPerformed);

        javax.swing.GroupLayout PnlOpcionesLayout = new javax.swing.GroupLayout(PnlOpciones);
        PnlOpciones.setLayout(PnlOpcionesLayout);
        PnlOpcionesLayout.setHorizontalGroup(
            PnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlOpcionesLayout.createSequentialGroup()
                .addGroup(PnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PnlOpcionesLayout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addGroup(PnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                                .addGroup(PnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JlbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlOpcionesLayout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(27, 27, 27)
                                            .addComponent(BtnOrden)
                                            .addGap(12, 12, 12))
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlOpcionesLayout.createSequentialGroup()
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(BtnUsuarios)
                                            .addGap(10, 10, 10))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlOpcionesLayout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(BtnPacientes)
                                            .addGap(8, 8, 8))
                                        .addComponent(jSeparator3)
                                        .addGroup(PnlOpcionesLayout.createSequentialGroup()
                                            .addGap(33, 33, 33)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(BtnConsultas)))
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlOpcionesLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(BtnHistorias)
                                .addGap(13, 13, 13))))
                    .addGroup(PnlOpcionesLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnUsuarios1)
                        .addGap(39, 39, 39)))
                .addContainerGap())
            .addGroup(PnlOpcionesLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlOpcionesLayout.setVerticalGroup(
            PnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlOpcionesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(JlbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(39, 39, 39)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlOpcionesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlOpcionesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PnlOpcionesLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlOpcionesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlOpcionesLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlOpcionesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(PnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlOpcionesLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlOpcionesLayout.createSequentialGroup()
                        .addComponent(BtnHistorias, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        PnlContenido.setBackground(new java.awt.Color(102, 255, 0));

        javax.swing.GroupLayout PnlContenidoLayout = new javax.swing.GroupLayout(PnlContenido);
        PnlContenido.setLayout(PnlContenidoLayout);
        PnlContenidoLayout.setHorizontalGroup(
            PnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        PnlContenidoLayout.setVerticalGroup(
            PnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PnlOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PnlContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(PnlContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Cargamos el panel de historias clinicas
    private void BtnHistoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHistoriasActionPerformed
        cardLayout.show(PnlContenido, "historias");
    }//GEN-LAST:event_BtnHistoriasActionPerformed

    //Cargamos el panel de consultas
    private void BtnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultasActionPerformed
        cardLayout.show(PnlContenido, "consultas");
    }//GEN-LAST:event_BtnConsultasActionPerformed

    //Cargamos el panel de ordenes
    private void BtnOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOrdenActionPerformed
        cardLayout.show(PnlContenido, "ordenes");
    }//GEN-LAST:event_BtnOrdenActionPerformed

    //Cargamos el panel de pacientes
    private void BtnPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPacientesActionPerformed
        cardLayout.show(PnlContenido, "pacientes");
    }//GEN-LAST:event_BtnPacientesActionPerformed

    //Cargamos el panel de usuarios
    private void BtnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUsuariosActionPerformed
        
        //Validamos si el usuario loggeado es de tipo Admin
        if(USesion.usuarioRol == 1){
            cardLayout.show(PnlContenido, "usuarios");
        }else{
            BtnUsuarios.setForeground(new java.awt.Color(120,120,120));
            JOptionPane.showMessageDialog(this, "No tienes permisos para acceder a esta sección.","Acceso denegado",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnUsuariosActionPerformed

    //Cargamos el panel de dashboard
    private void BtnUsuarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUsuarios1ActionPerformed
        Dashboard dash = new Dashboard();
        dash.cargarDashboard();
        cardLayout.show(PnlContenido, "dashboard");
    }//GEN-LAST:event_BtnUsuarios1ActionPerformed

    //Creamos un reloj que muestre fecha y hora actual
    private void iniciarReloj() {
        javax.swing.Timer timer = new javax.swing.Timer(1000, (e) -> {
            java.time.LocalDateTime ahora = java.time.LocalDateTime.now();
            String formato = ahora.format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));
            LblHora.setText(formato);
        });
        timer.start();
    }
    
    //Inicialisamos los paneles y los creamos
    private void cargarPaneles(){
        cardLayout = new CardLayout();
        PnlContenido.setLayout(cardLayout);
        PnlContenido.add(new Dashboard(), "dashboard");
        PnlContenido.add(new Usuarios(), "usuarios");
        PnlContenido.add(new Pacientes(), "pacientes");
        panelOrdenes = new Ordenes();
        panelConsultas = new Consultas(panelOrdenes);
        PnlContenido.add(panelOrdenes, "ordenes");
        PnlContenido.add(panelConsultas, "consultas");
        PnlContenido.add(new HistoriasClinicas(), "historias");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Home().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConsultas;
    private javax.swing.JButton BtnHistorias;
    private javax.swing.JButton BtnOrden;
    private javax.swing.JButton BtnPacientes;
    private javax.swing.JButton BtnUsuarios;
    private javax.swing.JButton BtnUsuarios1;
    private javax.swing.JLabel JlbUser;
    private javax.swing.JLabel LblHora;
    private javax.swing.JPanel PnlContenido;
    private javax.swing.JPanel PnlOpciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
